default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: dev_environment_development

test:
  <<: *default
  database: dev_environment_test

production:
  <<: *default
  database: dev_environment_production
  username: dev_environment
  password: <%= ENV['DEV_ENVIRONMENT_DATABASE_PASSWORD'] %>
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
